Vagrant.configure("2") do |config|
  # config.hostmanager.enabled = true 
  # config.hostmanager.manage_host = true
  
### apollo VM ###
  config.vm.define "apollo" do |apollo|
    apollo.vm.box = "ubuntu/bionic64"
    apollo.vm.hostname = "apollo"
	apollo.vm.network "private_network", ip: "192.168.56.11"
    apollo.vm.provider "virtualbox" do |vb|
      vb.memory = "5120"
    end
    apollo.vm.provision "shell", inline: <<-SHELL
     echo "export TERM=xterm-256color" >> ~/.bashrc
     source ~/.bashrc
    SHELL
  end
  
### juno VM ###
  config.vm.define "juno" do |juno|
    juno.vm.box = "ubuntu/bionic64"
    juno.vm.hostname = "juno"
	juno.vm.network "private_network", ip: "192.168.56.12"
    juno.vm.provider "virtualbox" do |vb|
        vb.memory = "3072"
    end
    juno.vm.provision "shell", inline: <<-SHELL
     echo "export TERM=xterm-256color" >> ~/.bashrc
     source ~/.bashrc
    SHELL
  end

### hera VM ###
  config.vm.define "hera" do |hera|
    hera.vm.box = "ubuntu/bionic64"
    hera.vm.hostname = "hera"
	hera.vm.network "private_network", ip: "192.168.56.13"
    hera.vm.provider "virtualbox" do |vb|
         vb.memory = "3072"
    end
    hera.vm.provision "shell", inline: <<-SHELL
     echo "export TERM=xterm-256color" >> ~/.bashrc
     source ~/.bashrc
    SHELL
  end

end 
